### PR TITLE
Kron improvements

### LINKED ISSUE #65: Performance improvement of Kron times Vector/Matrix
Up to now I was using v0.9.1 of LazyArrays and implemented an improved version of multiplying a Kron with a Vector/Matrix. After updating to v0.12.0 my code is not working 
anymore.

I'm writing a program for statistical analysis of data that makes heavy use of big matrices.
The memory requirement of the matrices that I'm using can easily go up to 100TB, way too big to store them directly in memory. Luckily my matrices are kronecker products of smaller matrices so i am using LazyArrays.Kron to represent them.

In my program i often need to multiply a Kron with a Vector or Matrix. Up to now i was using version 0.9.1 of LazyArrays and the way the multiplication is carried out there is not feasible for me (IIRC generic_matmatmul gets called and each element of the Kron is visited individually).

Therefore, I implemented my own version of `(*)(::Kron,::Vector)` or actually `mul!(::Vector, ::Kron, ::Vector)`. 
In essence it uses the property `Kron(A,B)*vec(X)=vec(B*X*A^T)` ([https://en.wikipedia.org/wiki/Kronecker_product#Matrix_equations](url)) to avoid creating a dense matrix and iterating through all elements of the matrix. If a matrix should be multiplied it does so by multiplying for each column using views of the columns to avoid memory allocation. Higher order kronecker products are handled recursively `Kron(A,B,C)*vec(X)=Kron(B,C)*(X*A^T)`. The actual implementation is of course a bit more complicated, especially for higher order kronecker products where chains of reshape/view occur (the BLAS functions don't like chains of reshape/view).
I was able to achieve a significant performance improvement w.r.t. the 0.9.1 version of LazyArrays and also the straigh-forward Julia implementation using `kron`(not for the huge matrices of course).
```
A=randn(ComplexF64,10,10);
B=randn(ComplexF64,10,10);
C=kron(A,B);
CK=Kron(A,B);
x=randn(size(CK,1));
C*x;CK*x; # warmup
@btime $CK*$x; #  6.861 μs (10 allocations: 6.88 KiB)
@btime $C*$x; #   21.639 μs (1 allocation: 3.25 KiB)
```
Please note that the benchmark for `kron` does not take into account the time it takes to compute `kron(A,B)` and still it performs worse. For higher order kronecker products the performance gain differs but is there and allows me to work with big matrices at all.

Without any changes to v0.9.1 i got this result
```
@btime $CK*$x; #  1.291 ms (1 allocation: 3.25 KiB)
``` 

Now for my actual question. I was updating LazyArrays from 0.9.1 to 0.12.0 and the way i implemented my improvement is not working anymore (my own version of `mul!`is not called anymore) and i'm wondering now what is the best place in the source code for my improvement. 
I do not fully understand all the changes from 0.9.1 to 0.12.0, all i could figure out for now is that ultimately `default_blasmul!` is called. Would that be an appropriate spot for my changes? Could i just implement a version of `default_blasmul!` that specializes on `Kron` or would that interfere with `apply, applied, ApplArray` or in general with the way multiplication is carried out in 0.12.0?

Thank you for any hints
BR
Martin 

PS: unfortunately i couldn't find the time in the past to clean-up my code and provide the improvements already for v0.9.1 but maybe it can be done now

### PR DESCRIPTION
**Pull request by emerali**
Resolves #65. 

Added materialize method for fast `Kron * AbstractVector` and `Kron * AbstractMatrix`, following the method detailed in this paper: http://yoksis.bilkent.edu.tr/pdf/files/11666.pdf (algorithms 1 & 3).
Also, a specialized `Kron * AbstractVector` for the case where the kronecker product only has two factors (the so-called "Vec Trick").

Minor additions: `logdet`, `logabsdet`, `diag`

Todo: 
- [x] tests
- [x] implement compatibility of Inv, Pinv, Adjoint and Transpose with Kron 
- [x] skip "modified shuffle" algorithm's initial step if the Kronecker factors can't be indexed/are lazy themselves ~~(need to think about how to implement this)~~

Possible todos:
- [x] another method for materialize in the case where both multiplication factors are Kron types
    - complication: need to check that factors are "aligned" before doing the factor-factor matmuls
- KronPow (matmul for this type [in the square case] ends up being a simple generalization of the Fast Walsh-Hadamard Transform and is therefore quite fast) and KronSum types?
    - admittedly, these may be outside of intended scope of project

### CODE REVIEW

File: src/lazyoperations.jl [hunk 1]
```diff
@@ -59,6 +100,181 @@ function tr(K::Kron{<:Any, 2})
...
+        d = similar(K.args[1], minimum(size(K)))
+        for i in 1:length(d)
+            d[i] = K[i,i]
+        end
+        return d
+    end
+end
+
+
+function LazyArrays.materialize(M::Applied{
```
Comment (dlfivefifty) [inline src/lazyoperations.jl]: No need for `LazyArrays.` here and below

Comment (emerali) [reply src/lazyoperations.jl]: oops! this was a hold-over from when i was playing around with this in jupyter :joy:

**Comment by emerali** [comment]
Hi there, I ended up getting busy with school work, so wasn't really able to keep up with this.

The PR as it is now *should* be OK to merge (modulo merge conflicts), but I have a couple questions/comments first

1. When multiplying 2 Kron types, the way I've implemented it now, materialize constructs the full matrix and returns that. This is because, as I understand it, the convention is for materialize to return a non-lazy array. Is my understanding correct? I think it'd make more sense in this case for Kron * Kron to give another Kron, so you can keep using the other optimized Kron methods with the result. I'm not sure how to do this without breaking the convention for materialize though.

2. For things like KronPow and KronSum, we'd need to make more types, and I'm worried this'll be straying out of the scope of LazyArrays. It might make more sense to spin Kronecker functionality out into a separate package entirely (we could still merge the current PR into LazyArrays for the time being, though). I came across a dedicated Kronecker package a while back (https://github.com/MichielStock/Kronecker.jl) that seems to do this, but is fairly rudimentary (eg. defines its structs recursively, making things like the shuffle algorithm difficult to implement). I did play around with it a little, and it *seems* to already be fairly compatible with LazyArrays since it's just a subtype of `AbstractMatrix`. Still, I'd like to know your thoughts on this.

**Comment by dlfivefifty** [comment]
> the convention is for materialize to return a non-lazy array

No this isn't the convention. Return a lazy array if that's appropriate.

> For things like KronPow and KronSum, we'd need to make more types, and I'm worried this'll be straying out of the scope of LazyArrays

I'm not sure I understand what these types are meant to do.

**Comment by emerali** [comment]
> Return a lazy array if that's appropriate.

this change has been made for compatible Kron by Kron matmuls

---

KronPow would just be an n-fold Kronecker product of a single matrix with itself

KronSum is definition 8 from: https://en.wikipedia.org/wiki/Kronecker_product#Relations_to_other_matrix_operations

They aren't too important though, so I won't add them in this PR (also I just don't think I'll have the time to implement them anytime soon).

**Comment by dlfivefifty** [comment]
Do you know why the tests are passing on Julia v1.4?

File: src/lazyoperations.jl [hunk 2]
```diff
@@ -41,24 +55,272 @@ function det(K::Kron{<:Any, 2})
...
+    # mixed-product property after explicitly computing the Kronecker product of
+    # the two factors of B (or maybe just deferring to the shuffle algorithm)
+    if (length(A.args) == length(B.args)) && all(_compatible_sizes, zip(A.args, B.args))
+        factors = [(A_i * B_i) for (A_i, B_i) in zip(A.args, B.args)]
+        return Kron(factors...)
+    else
+        algo_type = shuffle_algorithm_type(MT)
+        return shuffle_algorithm(algo_type, A, B, eltype(M))
+    end
+end
```
Comment (dlfivefifty) [inline src/lazyoperations.jl:135]: The following would be better to embrace the `MulAdd` type from ArrayLayouts.jl., to support in-place operations. For the case `(length(A.args) == length(B.args)) && all(_compatible_sizes, zip(A.args, B.args))` this seems fairly straightforward, something like:
```julia
similar(M::MulAdd{ApplyLayout{typeof(kron)}, ApplyLayout{typeof(kron)}, ::Type{T}) where T = Kron(similar.(MulAdd.(arguments(M.A), arguments(M.B)), T)...)

function materialize!(M:MulAdd{ApplyLayout{typeof(kron)}, ApplyLayout{typeof(kron)},ApplyLayout{typeof(kron)}})
   materialize!.(MulAdd.(M.α, arguments(M.A), arguments(M.B), M.β, arguments(M.C))
   M.C
end
```

Though I don't know how hard the other case would be... so happy to merge as is.

Technically you should be making a new `ApplyStyle` and not overload with `MulAddStyle`.

Comment (emerali) [reply src/lazyoperations.jl:135]: I don't understand the different `ApplyStyle`s or the types in ArrayLayouts.jl very well, so I'm not sure I'll be able to figure this out without help.

**Comment by emerali** [comment]
I'm not sure if the tests are even actually failing in Julia 1.4

It looks like they're just timing out on Travis for some reason, but the timeout seems to be happening before the Kron tests are even reached as far as i can tell.

**Comment by emerali** [comment]
hmm seems like there's a stack overflow happening, and i'm able to reproduce it locally too

i'll look into this

**Comment by dlfivefifty** [comment]
If you get stuck I can have a look: parts of the design of this package are unfortunately brittle (in that if you don't overload the right things you get stack overflows), which I'm slowly correcting.

**Comment by emerali** [comment]
I just gave it another attempt but i'm still unable to figure out what's causing the stack-overflow.

In addition to this, it appears that the materialize functions i defined are no longer being called. Not really sure how to fix them.

**Comment by dlfivefifty** [comment]
OK I'll have a look

**Comment by dlfivefifty** [comment]
OK I updated to the ArrayLayouts v0.4 system, so instead of `materialize(::Applied)` you overload `copy(::Mul)`.

**Comment by emerali** [comment]
Tests seem to be passing locally now and I've made sure the correct methods are being called.

need to wait to see what Travis thinks

File: src/lazyoperations.jl [hunk 3]
```diff
@@ -115,7 +115,12 @@ _compatible_sizes((A, B)) = (size(A, 2) == size(B, 1))
 
 # Implements the mixed-product property for the Kronecker product and matrix
 # multiplication
-function copy(M::Mul{ApplyLayout{typeof(kron)},ApplyLayout{typeof(kron)},<:AbstractMatrix,<:AbstractMatrix})
+function copy(M::Mul{
```
Comment (dlfivefifty) [inline src/lazyoperations.jl:118]: Why did you change the type signature? There is no reason to restrict to `Kron` as the `ApplyLayout` takes care of that/

**Review by dlfivefifty — CHANGES_REQUESTED** [review]

File: src/lazyoperations.jl (hunk 3 above)
Comment (emerali) [reply src/lazyoperations.jl:118]: i need to dispatch on the fact that both arguments here are `Kron` types or else it'll just go straight to the shuffle algo

Comment (dlfivefifty) [reply src/lazyoperations.jl:118]: No the first two `ApplyLayout{typeof(kron)}` tell you both are lazy kronecker products, you don't need to worry about the types of matrices.

Comment (emerali) [reply src/lazyoperations.jl:118]: oh you're right 

I think I got carried away when I fixed the vec-trick dispatch and just applied the same strategy here

**Comment by emerali** [comment]
i'll write a few more tests to get the coverage back up

**Comment by emerali** [comment]
ready to merge when you are

File: Project.toml [hunk 4]
```diff
@@ -5,9 +5,11 @@ version = "0.17.5"
 [deps]
 ArrayLayouts = "4c555306-a7a7-4459-81d9-ec55ddd5c99a"
 FillArrays = "1a297f60-69ca-5386-bcde-b61e274b549b"
+Future = "9fa8497b-333b-5362-9e8d-4d0656e87820"
```
Comment (dlfivefifty) [inline Project.toml:8]: Why is this added?

File: src/lazyoperations.jl [hunk 5]
```diff
@@ -41,24 +55,269 @@
...
+# multiplication
+function copy(M::Mul{ApplyLayout{typeof(kron)}, ApplyLayout{typeof(kron)}})
+    A, B = M.A, M.B
+    MT = promote_type(map(typeof, arguments(A))..., map(typeof,arguments(B))...)
+    # Keeping it simple for now, but could potentially make this "alignment"-check
+    # more precise. For example, if one factor of A has 6 columns and it's aligned
+    # with two factors of B with 2 and 3 rows, then we can still use the
+    # mixed-product property after explicitly computing the Kronecker product of
+    # the two factors of B (or maybe just deferring to the shuffle algorithm)
+    if (length(A.args) == length(B.args)) && all(_compatible_sizes, zip(A.args, B.args))
```
Comment (dlfivefifty) [inline src/lazyoperations.jl:126]: Use ` arguments(A) ` instead of ` A.args ` as ` A ` may potentially be a different type. Same with ` B.args `

File: src/lazyoperations.jl [hunk 6]
```diff
@@ -41,24 +55,269 @@
...
+        return shuffle_algorithm(algo_type, A, B, eltype(M))
+    end
+end
+
+
+# Implements Roth's lemma aka the "vec-trick" for multiplying a 2-factor Kron
+# matrix to a vector
+function copy(M::Mul{
+    LazyArrays.ApplyLayout{typeof(kron)},
+    <:ArrayLayouts.MemoryLayout,
```
Comment (dlfivefifty) [inline src/lazyoperations.jl:140]: Why this restriction?

**Review by dlfivefifty — CHANGES_REQUESTED** [review]

File: Project.toml (hunk 4 above)
Comment (emerali) [reply Project.toml:8]: not really sure, i'll remove it

File: src/lazyoperations.jl (hunk 5 above)
Comment (emerali) [reply src/lazyoperations.jl:126]: should i make this change everywhere, or just this function?

File: src/lazyoperations.jl (hunk 6 above)
Comment (emerali) [reply src/lazyoperations.jl:140]: changed ArrayLayouts.MemoryLayout back to Any

**Review by dlfivefifty — APPROVED** [review]
